# Site settings
title: Yulaf Beat
description: Yulaf Beat oficial website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yulaf Beat
user_description: I'm a freelance music producer about 1 year. I can make any genre hip-hop beats (eg. trap, drill, lo-fi). <br>Below, you can see some of my beats.
user_title: Music Producer
email: yulafbeat@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
